#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <mach-o/dyld.h>

static BOOL CEContainsAny(NSString *value, NSArray<NSString *> *needles) {
    if (value.length == 0) return NO;
    NSString *lower = value.lowercaseString;
    for (NSString *needle in needles) {
        if ([lower containsString:needle]) return YES;
    }
    return NO;
}

static BOOL CEIsUISuffixClass(NSString *name) {
    if (name.length == 0) return NO;
    NSArray *suffixes = @[@"View", @"VC", @"ViewController", @"Cell", @"Alert", @"PopView", @"Header", @"Footer"];
    for (NSString *suffix in suffixes) {
        if ([name hasSuffix:suffix]) return YES;
    }
    return NO;
}

static BOOL CEIsBlockedClassName(NSString *name) {
    if (name.length == 0) return NO;

    static NSSet<NSString *> *exact;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        exact = [NSSet setWithArray:@[
            @"MeariAdCustomView",
            @"MeariAddDevicePayAlertView",
            @"MeariBuyServiceAlertView",
            @"MeariOpenFreeCloudIntroView",
            @"MeariServiceDiscountAlert",
            @"MeariServiceDiscountBottomAlert",
            @"MeariServicePayAlertView",
            @"MeariServiceTrialAlert",
            @"MeariServiceSplashSkipView",
            @"MeariCloudStoragePromotionView",
            @"MeariCloudStorageRecommandView",
            @"MeariCloudStorageRecomandCell",
            @"MeariCameraCloudPlanAlertView",
            @"MeariCameraSettingCloudPlanVC",
            @"MeariCloudMessageAISummaryShowPopView",
            @"MeariCloudMessageAISummaryView",
            @"JumpTrialVC",
            @"WYCloudPromotionView",
            @"WYPromotionActivityView",
            @"WYAlarmVideoBuyTipView",
            @"AlarmVideoCloudBuyView",
            @"WYSimpleAlarmVideoCloudBuyView",
            @"OpenBasicCloudView",
            @"WYSimpleOpenBasicCloudView",
            @"WYMineServiceCell",
            @"WYMineCloudSaveCell",
            @"WYMsgAlarmDetailCloudBuyTableViewCell",
            @"WYServiceReceiveView",
            @"WYCloudPrivilegeView",
            @"WYCameraServiceDrawVC",
            @"WYAlarmMsgAIDescriptionIntroView",
            @"WYAlarmPlayAiAnalysisView",
            @"WYAIMarkView",
            @"WYAIAnalysisFeedbackView",
            @"WYVideoAIIconListView",
            @"WYSimpleAIIconListView",
            @"UIAISearchDeviceListView",
            @"UIAISearchDeviceListTableViewCell"
        ]];
    });

    if ([exact containsObject:name]) return YES;

    NSArray<NSString *> *alwaysPrefixes = @[
        @"MeariCameraSettingAI",
        @"MeariSettingAI",
        @"MeariAIAnalysis",
        @"MeariAIDetection",
        @"MeariAITrack",
        @"MeariAIService",
        @"WYCameraAISummary",
        @"WYAISearch",
        @"UIAISearch",
        @"WYCloudService",
        @"WYCloudPay",
        @"WYCloudOrder",
        @"WYMineHeaderPlan"
    ];
    for (NSString *prefix in alwaysPrefixes) {
        if ([name hasPrefix:prefix]) return YES;
    }

    if (CEIsUISuffixClass(name) &&
        ([name hasPrefix:@"MeariService"] ||
         [name hasPrefix:@"MeariCloudStorage"] ||
         [name hasPrefix:@"MeariSimTraffic"])) {
        return YES;
    }

    return NO;
}

static BOOL CETextLooksPromotional(NSString *text) {
    if (text.length == 0) return NO;

    static NSArray<NSString *> *phrases;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        phrases = @[
            @"cloud storage",
            @"cloud service",
            @"ai service",
            @"ai analysis",
            @"ai summary",
            @"ai search",
            @"intelligent ai",
            @"generated by ai",
            @"subscribe now",
            @"subscription",
            @"free trial",
            @"start trial",
            @"buy now",
            @"purchase now",
            @"upgrade plan",
            @"premium plan",
            @"vip subscription",
            @"special offer"
        ];
    });
    return CEContainsAny(text, phrases);
}

static void CEHideView(UIView *view) {
    if (!view) return;
    view.hidden = YES;
    view.alpha = 0.0;
    view.userInteractionEnabled = NO;
    view.accessibilityElementsHidden = YES;
}

static void CEScrubViewTree(UIView *view) {
    if (!view) return;

    NSString *className = NSStringFromClass(view.class);
    if (CEIsBlockedClassName(className)) {
        CEHideView(view);
        return;
    }

    if ([view isKindOfClass:UILabel.class]) {
        NSString *text = ((UILabel *)view).text;
        if (CETextLooksPromotional(text)) CEHideView(view);
    } else if ([view isKindOfClass:UIButton.class]) {
        UIButton *button = (UIButton *)view;
        NSString *title = [button titleForState:UIControlStateNormal];
        if (CETextLooksPromotional(title)) CEHideView(view);
    }

    for (UIView *subview in view.subviews.copy) {
        CEScrubViewTree(subview);
    }
}

static BOOL CEControllerShouldBeBlocked(UIViewController *controller) {
    if (!controller) return NO;
    if (CEIsBlockedClassName(NSStringFromClass(controller.class))) return YES;

    if ([controller isKindOfClass:UIAlertController.class]) {
        UIAlertController *alert = (UIAlertController *)controller;
        NSString *combined = [NSString stringWithFormat:@"%@ %@", alert.title ?: @"", alert.message ?: @""];
        if (CETextLooksPromotional(combined)) return YES;
    }
    return NO;
}

static void CEReplaceInstanceMethod(Class cls, SEL sel, IMP replacement) {
    if (!cls || !sel || !replacement) return;
    Method method = class_getInstanceMethod(cls, sel);
    if (!method) return;
    method_setImplementation(method, replacement);
}

static void CENoop0(id self, SEL _cmd) { (void)self; (void)_cmd; }
static void CENoop1(id self, SEL _cmd, id arg1) { (void)self; (void)_cmd; (void)arg1; }
static void CENoop2(id self, SEL _cmd, id arg1, id arg2) { (void)self; (void)_cmd; (void)arg1; (void)arg2; }
static BOOL CEReturnNO0(id self, SEL _cmd) { (void)self; (void)_cmd; return NO; }
static BOOL CEReturnNO1(id self, SEL _cmd, id arg1) { (void)self; (void)_cmd; (void)arg1; return NO; }
static id CEReturnNil0(id self, SEL _cmd) { (void)self; (void)_cmd; return nil; }
static id CEReturnNil1(id self, SEL _cmd, id arg1) { (void)self; (void)_cmd; (void)arg1; return nil; }
static id CEReturnEmptyArray0(id self, SEL _cmd) { (void)self; (void)_cmd; return @[]; }

static void (*CEOrigViewDidMoveToWindow)(UIView *, SEL);
static void CEViewDidMoveToWindow(UIView *self, SEL _cmd) {
    CEOrigViewDidMoveToWindow(self, _cmd);
    if (CEIsBlockedClassName(NSStringFromClass(self.class))) {
        CEHideView(self);
    }
}

static void (*CEOrigViewControllerViewDidAppear)(UIViewController *, SEL, BOOL);
static void CEViewControllerViewDidAppear(UIViewController *self, SEL _cmd, BOOL animated) {
    CEOrigViewControllerViewDidAppear(self, _cmd, animated);
    CEScrubViewTree(self.view);
}

static void (*CEOrigPresentViewController)(UIViewController *, SEL, UIViewController *, BOOL, void (^)(void));
static void CEPresentViewController(UIViewController *self, SEL _cmd, UIViewController *controller, BOOL animated, void (^completion)(void)) {
    if (CEControllerShouldBeBlocked(controller)) {
        if (completion) completion();
        return;
    }
    CEOrigPresentViewController(self, _cmd, controller, animated, completion);
}

static void (*CEOrigPushViewController)(UINavigationController *, SEL, UIViewController *, BOOL);
static void CEPushViewController(UINavigationController *self, SEL _cmd, UIViewController *controller, BOOL animated) {
    if (CEControllerShouldBeBlocked(controller)) return;
    CEOrigPushViewController(self, _cmd, controller, animated);
}

static void (*CEOrigLabelSetText)(UILabel *, SEL, NSString *);
static void CELabelSetText(UILabel *self, SEL _cmd, NSString *text) {
    CEOrigLabelSetText(self, _cmd, text);
    if (CETextLooksPromotional(text)) CEHideView(self);
}

static void (*CEOrigButtonSetTitle)(UIButton *, SEL, NSString *, UIControlState);
static void CEButtonSetTitle(UIButton *self, SEL _cmd, NSString *title, UIControlState state) {
    CEOrigButtonSetTitle(self, _cmd, title, state);
    if (CETextLooksPromotional(title)) CEHideView(self);
}

static void CEInstallKnownHooks(void) {
    Class launch = objc_getClass("MeariLaunchAdModule");
    if (launch) {
        CEReplaceInstanceMethod(launch, @selector(setup), (IMP)CENoop0);
        CEReplaceInstanceMethod(launch, @selector(loadDataOnly), (IMP)CENoop0);
        CEReplaceInstanceMethod(launch, @selector(showLaunchAdWithMeariLaunchAdModel:), (IMP)CENoop1);
        CEReplaceInstanceMethod(launch, @selector(handleSkipAdData), (IMP)CENoop0);
        CEReplaceInstanceMethod(launch, @selector(needRequestData), (IMP)CEReturnNO0);
        CEReplaceInstanceMethod(launch, @selector(cachedAdModel), (IMP)CEReturnNil0);
    }

    Class service = objc_getClass("MeariServiceBuyModule");
    if (service) {
        CEReplaceInstanceMethod(service, @selector(promptCloudStorageFreeTrial:inVC:), (IMP)CENoop2);
        CEReplaceInstanceMethod(service, @selector(promptCloudStorageBuy:inVC:), (IMP)CENoop2);
        CEReplaceInstanceMethod(service, @selector(showSplashAd), (IMP)CENoop0);
        CEReplaceInstanceMethod(service, @selector(canShowHomeBanner), (IMP)CEReturnNO0);
        CEReplaceInstanceMethod(service, @selector(canShowPreviewBanner:), (IMP)CEReturnNO1);
        CEReplaceInstanceMethod(service, @selector(canShowHomeDiscountRedDot), (IMP)CEReturnNO0);
        CEReplaceInstanceMethod(service, @selector(canAlertBindingService:), (IMP)CEReturnNO1);
        CEReplaceInstanceMethod(service, @selector(canTipBindingServiceFromLocalData), (IMP)CEReturnNO0);

        NSArray<NSString *> *nilSelectors = @[
            @"getHomeDiscountBannerModel",
            @"getHomeDiscountAlertModel",
            @"getHomeDiscountBottomAlertModel",
            @"getHomePromotionBannerModel",
            @"getHomePromotionAlertModel",
            @"getCloudDiscountModel",
            @"getAIDiscountModel",
            @"get4GDiscountModel",
            @"getCouponDiscountModel",
            @"splashAdModel",
            @"iconOnRightTopHomeModel",
            @"iconOnHomeListCardModel",
            @"atSecondAlarmMsgModel",
            @"previewGuideModel",
            @"photoPlaybackModel",
            @"videoPlaybackModel",
            @"_previewTrialAlertModel",
            @"alertOnCenterHome",
            @"alertOnBottomHome"
        ];
        for (NSString *selectorName in nilSelectors) {
            CEReplaceInstanceMethod(service, NSSelectorFromString(selectorName), (IMP)CEReturnNil0);
        }

        NSArray<NSString *> *nilOneArgSelectors = @[
            @"getHomePromotionModel:",
            @"getHomeDiscountModel:"
        ];
        for (NSString *selectorName in nilOneArgSelectors) {
            CEReplaceInstanceMethod(service, NSSelectorFromString(selectorName), (IMP)CEReturnNil1);
        }

        NSArray<NSString *> *emptyArraySelectors = @[
            @"bannerListOnTopHome",
            @"bannerListOnBottomHome",
            @"operationPointList"
        ];
        for (NSString *selectorName in emptyArraySelectors) {
            CEReplaceInstanceMethod(service, NSSelectorFromString(selectorName), (IMP)CEReturnEmptyArray0);
        }
    }

    NSArray<NSString *> *showClasses = @[
        @"MeariBuyServiceAlertView",
        @"MeariCloudStorageBindSuccessView",
        @"MeariServiceDiscountAlert",
        @"MeariServiceDiscountBottomAlert",
        @"MeariServicePaySuccessAlertView",
        @"MeariServiceTrialAlert"
    ];
    for (NSString *className in showClasses) {
        Class cls = objc_getClass(className.UTF8String);
        if (!cls) continue;
        CEReplaceInstanceMethod(cls, @selector(show), (IMP)CENoop0);
    }
}

static void CEInstallUIKitHooks(void) {
    Method m;

    m = class_getInstanceMethod(UIView.class, @selector(didMoveToWindow));
    if (m) {
        CEOrigViewDidMoveToWindow = (void *)method_getImplementation(m);
        method_setImplementation(m, (IMP)CEViewDidMoveToWindow);
    }

    m = class_getInstanceMethod(UIViewController.class, @selector(viewDidAppear:));
    if (m) {
        CEOrigViewControllerViewDidAppear = (void *)method_getImplementation(m);
        method_setImplementation(m, (IMP)CEViewControllerViewDidAppear);
    }

    m = class_getInstanceMethod(UIViewController.class, @selector(presentViewController:animated:completion:));
    if (m) {
        CEOrigPresentViewController = (void *)method_getImplementation(m);
        method_setImplementation(m, (IMP)CEPresentViewController);
    }

    m = class_getInstanceMethod(UINavigationController.class, @selector(pushViewController:animated:));
    if (m) {
        CEOrigPushViewController = (void *)method_getImplementation(m);
        method_setImplementation(m, (IMP)CEPushViewController);
    }

    m = class_getInstanceMethod(UILabel.class, @selector(setText:));
    if (m) {
        CEOrigLabelSetText = (void *)method_getImplementation(m);
        method_setImplementation(m, (IMP)CELabelSetText);
    }

    m = class_getInstanceMethod(UIButton.class, @selector(setTitle:forState:));
    if (m) {
        CEOrigButtonSetTitle = (void *)method_getImplementation(m);
        method_setImplementation(m, (IMP)CEButtonSetTitle);
    }
}

static void CEImageLoaded(const struct mach_header *mh, intptr_t vmaddr_slide) {
    (void)mh;
    (void)vmaddr_slide;
    dispatch_async(dispatch_get_main_queue(), ^{
        CEInstallKnownHooks();
    });
}

__attribute__((constructor))
static void CEInit(void) {
    @autoreleasepool {
        NSString *bundleID = NSBundle.mainBundle.bundleIdentifier;
        if (![bundleID isEqualToString:@"com.meari.smartcamera"]) return;

        CEInstallUIKitHooks();
        CEInstallKnownHooks();
        _dyld_register_func_for_add_image(CEImageLoaded);

        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            CEInstallKnownHooks();
            UIWindow *window = UIApplication.sharedApplication.windows.firstObject;
            CEScrubViewTree(window);
        });
    }
}
