#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <objc/runtime.h>

static char CETextScrubberHiddenKey;

static BOOL CEContainsAny(NSString *value, NSArray<NSString *> *needles) {
    if (value.length == 0) return NO;
    NSString *lower = value.lowercaseString;
    for (NSString *needle in needles) {
        if ([lower containsString:needle]) return YES;
    }
    return NO;
}

static BOOL CEIsUISuffixClass(NSString *name) {
    if (name.length == 0) return NO;

    static NSArray<NSString *> *suffixes;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        suffixes = @[@"View", @"VC", @"ViewController", @"Cell", @"Alert", @"PopView", @"Header", @"Footer"];
    });

    for (NSString *suffix in suffixes) {
        if ([name hasSuffix:suffix]) return YES;
    }
    return NO;
}

static BOOL CEIsBlockedClassName(NSString *name) {
    if (name.length == 0) return NO;

    static NSSet<NSString *> *exact;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        exact = [NSSet setWithArray:@[
            @"MeariAdCustomView",
            @"MeariAddDevicePayAlertView",
            @"MeariBuyServiceAlertView",
            @"MeariOpenFreeCloudIntroView",
            @"MeariServiceDiscountAlert",
            @"MeariServiceDiscountBottomAlert",
            @"MeariServicePayAlertView",
            @"MeariServiceTrialAlert",
            @"MeariServiceSplashSkipView",
            @"MeariCloudStoragePromotionView",
            @"MeariCloudStorageRecommandView",
            @"MeariCloudStorageRecomandCell",
            @"MeariCameraCloudPlanAlertView",
            @"MeariCameraSettingCloudPlanVC",
            @"MeariCloudMessageAISummaryShowPopView",
            @"MeariCloudMessageAISummaryView",
            @"JumpTrialVC",
            @"WYCloudPromotionView",
            @"WYPromotionActivityView",
            @"OpenBasicCloudView",
            @"WYSimpleOpenBasicCloudView",
            @"WYMineServiceCell",
            @"WYMineCloudSaveCell",
            @"WYServiceReceiveView",
            @"WYCloudPrivilegeView",
            @"WYCameraServiceDrawVC",
            @"WYAlarmMsgAIDescriptionIntroView",
            @"WYAIMarkView",
            @"WYAIAnalysisFeedbackView",
            @"WYVideoAIIconListView",
            @"WYSimpleAIIconListView",
            @"UIAISearchDeviceListView",
            @"UIAISearchDeviceListTableViewCell",
            @"WYAIEyeItem"
        ]];
    });

    if ([exact containsObject:name]) return YES;

    static NSArray<NSString *> *alwaysPrefixes;
    static dispatch_once_t prefixOnceToken;
    dispatch_once(&prefixOnceToken, ^{
        alwaysPrefixes = @[
            @"MeariCameraSettingAI",
            @"MeariSettingAI",
            @"MeariAIAnalysis",
            @"MeariAIDetection",
            @"MeariAITrack",
            @"MeariAIService",
            @"WYCameraAISummary",
            @"WYAISearch",
            @"UIAISearch",
            @"WYCloudService",
            @"WYCloudPay",
            @"WYCloudOrder",
            @"WYMineHeaderPlan"
        ];
    });
    for (NSString *prefix in alwaysPrefixes) {
        if ([name hasPrefix:prefix]) return YES;
    }

    if (CEIsUISuffixClass(name) &&
        ([name hasPrefix:@"MeariService"] ||
         [name hasPrefix:@"MeariCloudStorage"] ||
         [name hasPrefix:@"MeariSimTraffic"])) {
        return YES;
    }

    return NO;
}

static BOOL CETextLooksPromotional(NSString *text) {
    if (text.length == 0) return NO;

    static NSArray<NSString *> *phrases;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        phrases = @[
            @"cloud storage",
            @"cloud service",
            @"ai service",
            @"ai analysis",
            @"intelligent analysis",
            @"ai summary",
            @"ai search",
            @"intelligent ai",
            @"generated by ai",
            @"subscribe now",
            @"subscription",
            @"free trial",
            @"start trial",
            @"buy now",
            @"purchase now",
            @"upgrade plan",
            @"premium plan",
            @"vip subscription",
            @"special offer"
        ];
    });
    return CEContainsAny(text, phrases);
}

static void CEHideView(UIView *view) {
    if (!view) return;
    view.hidden = YES;
    view.alpha = 0.0;
    view.userInteractionEnabled = NO;
    view.accessibilityElementsHidden = YES;
}

static void CEScrubViewTree(UIView *view) {
    if (!view) return;

    NSString *className = NSStringFromClass(view.class);
    if (CEIsBlockedClassName(className)) {
        CEHideView(view);
        return;
    }

    if ([view isKindOfClass:UILabel.class]) {
        UILabel *label = (UILabel *)view;
        NSString *text = label.text;
        if (CETextLooksPromotional(text)) {
            objc_setAssociatedObject(label, &CETextScrubberHiddenKey, @YES, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
            CEHideView(label);
        } else if ([objc_getAssociatedObject(label, &CETextScrubberHiddenKey) boolValue]) {
            label.hidden = NO;
            label.alpha = 1.0;
            label.accessibilityElementsHidden = NO;
            objc_setAssociatedObject(label, &CETextScrubberHiddenKey, nil, OBJC_ASSOCIATION_ASSIGN);
        }
    } else if ([view isKindOfClass:UIButton.class]) {
        UIButton *button = (UIButton *)view;
        NSString *title = [button titleForState:UIControlStateNormal];
        if (CETextLooksPromotional(title)) {
            objc_setAssociatedObject(button, &CETextScrubberHiddenKey, @YES, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
            CEHideView(button);
        } else if ([objc_getAssociatedObject(button, &CETextScrubberHiddenKey) boolValue]) {
            button.hidden = NO;
            button.alpha = 1.0;
            button.userInteractionEnabled = YES;
            button.accessibilityElementsHidden = NO;
            objc_setAssociatedObject(button, &CETextScrubberHiddenKey, nil, OBJC_ASSOCIATION_ASSIGN);
        }
    }

    for (UIView *subview in view.subviews.copy) {
        CEScrubViewTree(subview);
    }
}

static BOOL CEControllerShouldBeBlocked(UIViewController *controller) {
    if (!controller) return NO;
    if (CEIsBlockedClassName(NSStringFromClass(controller.class))) return YES;

    if ([controller isKindOfClass:UIAlertController.class]) {
        UIAlertController *alert = (UIAlertController *)controller;
        NSString *combined = [NSString stringWithFormat:@"%@ %@", alert.title ?: @"", alert.message ?: @""];
        if (CETextLooksPromotional(combined)) return YES;
    }
    return NO;
}

static void CEReplaceInstanceMethod(Class cls, SEL sel, IMP replacement) {
    if (!cls || !sel || !replacement) return;
    Method method = class_getInstanceMethod(cls, sel);
    if (!method) return;

    const char *types = method_getTypeEncoding(method);
    if (class_addMethod(cls, sel, replacement, types)) {
        return;
    }

    Method ownMethod = class_getInstanceMethod(cls, sel);
    if (ownMethod) method_setImplementation(ownMethod, replacement);
}

static void CENoop0(id self, SEL _cmd) { (void)self; (void)_cmd; }
static void CENoop1(id self, SEL _cmd, id arg1) { (void)self; (void)_cmd; (void)arg1; }
static void CENoop2(id self, SEL _cmd, id arg1, id arg2) { (void)self; (void)_cmd; (void)arg1; (void)arg2; }
static BOOL CEReturnNO0(id self, SEL _cmd) { (void)self; (void)_cmd; return NO; }
static BOOL CEReturnNO1(id self, SEL _cmd, id arg1) { (void)self; (void)_cmd; (void)arg1; return NO; }
static id CEReturnNil0(id self, SEL _cmd) { (void)self; (void)_cmd; return nil; }
static id CEReturnNil1(id self, SEL _cmd, id arg1) { (void)self; (void)_cmd; (void)arg1; return nil; }
static id CEReturnEmptyArray0(id self, SEL _cmd) { (void)self; (void)_cmd; return @[]; }

static void (*CEOrigViewDidMoveToWindow)(UIView *, SEL);
static void CEViewDidMoveToWindow(UIView *self, SEL _cmd) {
    CEOrigViewDidMoveToWindow(self, _cmd);

    const char *rawName = class_getName(self.class);
    if (!rawName || rawName[0] == '\0') return;

    char first = rawName[0];
    BOOL possiblePromoClass =
        first == 'M' ||
        first == 'W' ||
        first == 'J' ||
        first == 'O' ||
        first == 'A' ||
        (first == 'U' && strncmp(rawName, "UIAI", 4) == 0);

    if (!possiblePromoClass) return;

    if (CEIsBlockedClassName([NSString stringWithUTF8String:rawName])) {
        CEHideView(self);
    }
}

static void (*CEOrigPresentViewController)(UIViewController *, SEL, UIViewController *, BOOL, void (^)(void));
static void CEPresentViewController(UIViewController *self, SEL _cmd, UIViewController *controller, BOOL animated, void (^completion)(void)) {
    if (CEControllerShouldBeBlocked(controller)) {
        if (completion) completion();
        return;
    }
    CEOrigPresentViewController(self, _cmd, controller, animated, completion);
}

static void (*CEOrigPushViewController)(UINavigationController *, SEL, UIViewController *, BOOL);
static void CEPushViewController(UINavigationController *self, SEL _cmd, UIViewController *controller, BOOL animated) {

    if (CEControllerShouldBeBlocked(controller)) return;
    CEOrigPushViewController(self, _cmd, controller, animated);
}


static void (*CEOrigDeviceSettingCellLayoutSubviews)(id, SEL) = NULL;
static BOOL CEDeviceSettingCellHookInstalled = NO;

static void CEDeviceSettingCellLayoutSubviews(id self, SEL _cmd) {
    if (CEOrigDeviceSettingCellLayoutSubviews) {
        CEOrigDeviceSettingCellLayoutSubviews(self, _cmd);
    }

    if ([self isKindOfClass:UIView.class]) {
        CEScrubViewTree((UIView *)self);
    }
}

static void CEInstallDeviceSettingCellHook(void) {
    if (CEDeviceSettingCellHookInstalled) return;

    Class cls = objc_getClass("MeariDeviceSettingItemCell");
    if (!cls) return;

    SEL sel = @selector(layoutSubviews);
    Method method = class_getInstanceMethod(cls, sel);
    if (!method) return;

    IMP original = method_getImplementation(method);
    const char *types = method_getTypeEncoding(method);

    if (class_addMethod(cls, sel, (IMP)CEDeviceSettingCellLayoutSubviews, types)) {
        CEOrigDeviceSettingCellLayoutSubviews = (void (*)(id, SEL))original;
    } else {
        Method ownMethod = class_getInstanceMethod(cls, sel);
        CEOrigDeviceSettingCellLayoutSubviews =
            (void (*)(id, SEL))method_setImplementation(ownMethod,
                                                        (IMP)CEDeviceSettingCellLayoutSubviews);
    }

    CEDeviceSettingCellHookInstalled = YES;
}

static char CEAlarmPromoIndexPathKey;
static CGFloat (*CEOrigAlarmSortHeightForRow)(id, SEL, UITableView *, NSIndexPath *) = NULL;
static id (*CEOrigAlarmSortCellForRow)(id, SEL, UITableView *, NSIndexPath *) = NULL;
static BOOL CEAlarmPromoRowHookInstalled = NO;

static BOOL CEIsAlarmCloudBuyCell(id cell) {
    if (!cell) return NO;

    Class promoClass = objc_getClass("WYMsgAlarmDetailCloudBuyTableViewCell");
    return promoClass && [cell isKindOfClass:promoClass];
}

static CGFloat CEAlarmSortHeightForRow(id self, SEL _cmd, UITableView *tableView, NSIndexPath *indexPath) {
    NSIndexPath *knownPromo =
        objc_getAssociatedObject(self, &CEAlarmPromoIndexPathKey);

    if (knownPromo && [knownPromo isEqual:indexPath]) {
        return 0.01;
    }

    UITableViewCell *visibleCell = [tableView cellForRowAtIndexPath:indexPath];
    if (CEIsAlarmCloudBuyCell(visibleCell)) {
        objc_setAssociatedObject(self,
                                 &CEAlarmPromoIndexPathKey,
                                 indexPath,
                                 OBJC_ASSOCIATION_COPY_NONATOMIC);
        return 0.01;
    }

    if (!CEOrigAlarmSortHeightForRow) return 0.0;
    return CEOrigAlarmSortHeightForRow(self, _cmd, tableView, indexPath);
}

static id CEAlarmSortCellForRow(id self, SEL _cmd, UITableView *tableView, NSIndexPath *indexPath) {
    id cell = CEOrigAlarmSortCellForRow ?
        CEOrigAlarmSortCellForRow(self, _cmd, tableView, indexPath) : nil;

    if (CEIsAlarmCloudBuyCell(cell)) {
        objc_setAssociatedObject(self,
                                 &CEAlarmPromoIndexPathKey,
                                 indexPath,
                                 OBJC_ASSOCIATION_COPY_NONATOMIC);

        if ([cell isKindOfClass:UIView.class]) {
            CEHideView((UIView *)cell);
        }

        __weak UITableView *weakTable = tableView;
        dispatch_async(dispatch_get_main_queue(), ^{
            UITableView *strongTable = weakTable;
            if (!strongTable || !strongTable.window) return;
            [strongTable beginUpdates];
            [strongTable endUpdates];
        });
    }

    return cell;
}

static void CEInstallAlarmPromoRowHookForClass(Class cls) {
    if (CEAlarmPromoRowHookInstalled || !cls) return;
    if (strcmp(class_getName(cls), "WYMsgAlarmDetailSortVC") != 0) return;

    Method heightMethod =
        class_getInstanceMethod(cls, @selector(tableView:heightForRowAtIndexPath:));
    Method cellMethod =
        class_getInstanceMethod(cls, @selector(tableView:cellForRowAtIndexPath:));
    if (!heightMethod || !cellMethod) return;

    CEOrigAlarmSortHeightForRow =
        (CGFloat (*)(id, SEL, UITableView *, NSIndexPath *))
        method_getImplementation(heightMethod);
    CEOrigAlarmSortCellForRow =
        (id (*)(id, SEL, UITableView *, NSIndexPath *))
        method_getImplementation(cellMethod);

    method_setImplementation(heightMethod, (IMP)CEAlarmSortHeightForRow);
    method_setImplementation(cellMethod, (IMP)CEAlarmSortCellForRow);
    CEAlarmPromoRowHookInstalled = YES;
}

static void CEInstallAlarmPromoRowHook(void) {
    CEInstallAlarmPromoRowHookForClass(objc_getClass("WYMsgAlarmDetailSortVC"));
}

static void (*CEOrigTableViewSetDelegate)(UITableView *, SEL, id) = NULL;

static void CETableViewSetDelegate(UITableView *self, SEL _cmd, id delegate) {
    CEOrigTableViewSetDelegate(self, _cmd, delegate);

    if (!delegate) return;
    Class cls = object_getClass(delegate);
    (void)cls;

    const char *name = class_getName([delegate class]);
    if (name && strcmp(name, "WYMsgAlarmDetailSortVC") == 0) {
        CEInstallAlarmPromoRowHookForClass([delegate class]);
    }
}

static void CEInstallKnownHooks(void) {
    CEInstallDeviceSettingCellHook();
    CEInstallAlarmPromoRowHook();

    Class launch = objc_getClass("MeariLaunchAdModule");
    if (launch) {
        CEReplaceInstanceMethod(launch, @selector(setup), (IMP)CENoop0);
        CEReplaceInstanceMethod(launch, @selector(loadDataOnly), (IMP)CENoop0);
        CEReplaceInstanceMethod(launch, @selector(showLaunchAdWithMeariLaunchAdModel:), (IMP)CENoop1);
        CEReplaceInstanceMethod(launch, @selector(handleSkipAdData), (IMP)CENoop0);
        CEReplaceInstanceMethod(launch, @selector(needRequestData), (IMP)CEReturnNO0);
        CEReplaceInstanceMethod(launch, @selector(cachedAdModel), (IMP)CEReturnNil0);
    }

    Class service = objc_getClass("MeariServiceBuyModule");
    if (service) {
        CEReplaceInstanceMethod(service, @selector(promptCloudStorageFreeTrial:inVC:), (IMP)CENoop2);
        CEReplaceInstanceMethod(service, @selector(promptCloudStorageBuy:inVC:), (IMP)CENoop2);
        CEReplaceInstanceMethod(service, @selector(showSplashAd), (IMP)CENoop0);
        CEReplaceInstanceMethod(service, @selector(canShowHomeBanner), (IMP)CEReturnNO0);
        CEReplaceInstanceMethod(service, @selector(canShowPreviewBanner:), (IMP)CEReturnNO1);
        CEReplaceInstanceMethod(service, @selector(canShowHomeDiscountRedDot), (IMP)CEReturnNO0);
        CEReplaceInstanceMethod(service, @selector(canAlertBindingService:), (IMP)CEReturnNO1);
        CEReplaceInstanceMethod(service, @selector(canTipBindingServiceFromLocalData), (IMP)CEReturnNO0);

        NSArray<NSString *> *nilSelectors = @[
            @"getHomeDiscountBannerModel",
            @"getHomeDiscountAlertModel",
            @"getHomeDiscountBottomAlertModel",
            @"getHomePromotionBannerModel",
            @"getHomePromotionAlertModel",
            @"getCloudDiscountModel",
            @"getAIDiscountModel",
            @"get4GDiscountModel",
            @"getCouponDiscountModel",
            @"splashAdModel",
            @"iconOnRightTopHomeModel",
            @"iconOnHomeListCardModel",
            @"previewGuideModel",
            @"_previewTrialAlertModel",
            @"alertOnCenterHome",
            @"alertOnBottomHome"
        ];
        for (NSString *selectorName in nilSelectors) {
            CEReplaceInstanceMethod(service, NSSelectorFromString(selectorName), (IMP)CEReturnNil0);
        }

        NSArray<NSString *> *nilOneArgSelectors = @[
            @"getHomePromotionModel:",
            @"getHomeDiscountModel:"
        ];
        for (NSString *selectorName in nilOneArgSelectors) {
            CEReplaceInstanceMethod(service, NSSelectorFromString(selectorName), (IMP)CEReturnNil1);
        }

        NSArray<NSString *> *emptyArraySelectors = @[
            @"bannerListOnTopHome",
            @"bannerListOnBottomHome"
        ];
        for (NSString *selectorName in emptyArraySelectors) {
            CEReplaceInstanceMethod(service, NSSelectorFromString(selectorName), (IMP)CEReturnEmptyArray0);
        }
    }

    NSArray<NSString *> *showClasses = @[
        @"MeariBuyServiceAlertView",
        @"MeariCloudStorageBindSuccessView",
        @"MeariServiceDiscountAlert",
        @"MeariServiceDiscountBottomAlert",
        @"MeariServicePaySuccessAlertView",
        @"MeariServiceTrialAlert"
    ];
    for (NSString *className in showClasses) {
        Class cls = objc_getClass(className.UTF8String);
        if (!cls) continue;
        CEReplaceInstanceMethod(cls, @selector(show), (IMP)CENoop0);
    }
}

static void CEInstallUIKitHooks(void) {
    Method m;

    m = class_getInstanceMethod(UITableView.class, @selector(setDelegate:));
    if (m) {
        CEOrigTableViewSetDelegate =
            (void (*)(UITableView *, SEL, id))method_getImplementation(m);
        method_setImplementation(m, (IMP)CETableViewSetDelegate);
    }

    m = class_getInstanceMethod(UIView.class, @selector(didMoveToWindow));
    if (m) {
        CEOrigViewDidMoveToWindow = (void (*)(UIView *, SEL))method_getImplementation(m);
        method_setImplementation(m, (IMP)CEViewDidMoveToWindow);
    }

    m = class_getInstanceMethod(UIViewController.class, @selector(presentViewController:animated:completion:));
    if (m) {
        CEOrigPresentViewController = (void (*)(UIViewController *, SEL, UIViewController *, BOOL, void (^)(void)))method_getImplementation(m);
        method_setImplementation(m, (IMP)CEPresentViewController);
    }

    m = class_getInstanceMethod(UINavigationController.class, @selector(pushViewController:animated:));
    if (m) {
        CEOrigPushViewController = (void (*)(UINavigationController *, SEL, UIViewController *, BOOL))method_getImplementation(m);
        method_setImplementation(m, (IMP)CEPushViewController);
    }

}

__attribute__((constructor))
static void CEInit(void) {
    @autoreleasepool {
        NSString *bundleID = NSBundle.mainBundle.bundleIdentifier;
        if (![bundleID isEqualToString:@"com.meari.smartcamera"]) return;

        CEInstallUIKitHooks();
        CEInstallKnownHooks();

    }
}
